# Generated by Django 5.0.6 on 2024-06-15 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorito',
        ),
    ]
