# Generated by Django 5.0.6 on 2024-06-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_estado_producto_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=130),
        ),
    ]
