# Generated by Django 5.0.6 on 2024-06-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='desc',
            field=models.CharField(max_length=240),
        ),
    ]
