# Generated by Django 5.0.6 on 2024-06-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.ImageField(blank=True, default=None, upload_to='uploads/product/'),
        ),
    ]
