# Generated by Django 5.0.6 on 2024-06-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_producto_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fechacreacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
